import type { Metadata } from "next";
import { Inter,Poppins } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import Scroll from "@/components/ScrollToTop";
import { ThemeProvider } from "@/providers/theme-provider";
import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/sonner";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import "/node_modules/flag-icons/css/flag-icons.min.css";
import "./theme/text-theme.css"

const inter = Inter({ subsets: ["latin"] });
const poppin = Poppins({ subsets:["latin"],weight:["400","500"] });

export const metadata: Metadata = {
  title: "Tuon's Next app boilerplate",
  description: "Generated by Tuon",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body className={poppin.className} suppressHydrationWarning>
        <Scroll />
        <NextIntlClientProvider messages={messages}>
          <ReactQueryProvider>
            <ThemeProvider enableSystem defaultTheme="system" attribute="class">
              <main className="py-10">
                <Navbar />
                {children}
              </main>
              <Toaster richColors position="top-center" />
            </ThemeProvider>
          </ReactQueryProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
